### ISSUE TITLE
File Control Invalid Class

### ISSUE THREAD

**Issue by zepernick** [struts-community-plugins/struts2-bootstrap#1]
The <input type="file"> is receiving the class "form-control" which is causing the height of the file button to extend outside of the border wrapping around it.  This issue can be seen happening in the [showcase](http://struts.jgeppert.com/struts2-bootstrap-showcase/index.action) as well.  The file input [example](http://getbootstrap.com/css/#forms-example) on the Bootstrap docs does not show this class being assigned.  I have dug through the template and see that it is including from the Struts simple theme.  I have not been able to figure out how in the world it is getting in there other than class is getting pushed into common-attributes or dynamic-attributes somewhere in the bootstrap template???

Here is a CSS workaround that we are currently using to fix the problem:

```css
input[type='file'].form-control  {
	height: auto;
}
```

**Comment by jogep** [comment]
New version 2.0.4 with fix is out now!
