### ISSUE TITLE
radiomap.ftl  missing dynamic-attributes.ftl

### ISSUE THREAD

**Issue by vnn456** [struts-community-plugins/struts2-bootstrap#10]

**Comment by max-trappist** [comment]
I had the same requirement so I changed the file radiomap.ftl to add support for dynamic attributes.
I think I will post a pull request to jogep.

**Comment by jogep** [comment]
PR is always welcome. ;-)

**Comment by max-trappist** [comment]
I added PR #18, hope can be useful

**Comment by sdutry** [comment]
this was merged with PR #18 and is present in release `2.5.1`
