### ISSUE TITLE
Allow thème override

### ISSUE THREAD

**Issue by jflefebvre06** [struts-community-plugins/struts2-bootstrap#12]
Could you please replace 
<#include "/${parameters.templateDir}/bootstrap/xxx" />
By
<#include "/${parameters.templateDir}/${parameters.name}/xxx" />
To allow thème override?

**Comment by jogep** [comment]
Sorry but it does not work with use of ${parameters.name} because this is the name of the field and not the name of the template. But you can specify your own template directory.
Also check following struts2 documentation.

https://struts.apache.org/docs/template-loading.html
