### ISSUE TITLE
Problem to compile

### ISSUE THREAD

**Issue by simone1391** [struts-community-plugins/struts2-bootstrap#17]
I have this problem 
<img width="1172" alt="schermata 2016-10-17 alle 23 21 35" src="https://cloud.githubusercontent.com/assets/6342684/19456183/926e19d0-94c0-11e6-8d44-06b555435d94.png">

How can I solve this problem?

**Comment by flofourcade** [comment]
The answer is in your screenshot. The bootstrap plugin depends on the jquery plugins. You re trying to build the snapshot version, which depends on jquery plugin snapshot version. So you have to solution.
Build and install the jquery plugin in your local repo, or enable the snapshot repository, as stated in readme.md.
