### ISSUE TITLE
Radio button field error generates double span with the same message

### ISSUE THREAD

**Issue by max-trappist** [struts-community-plugins/struts2-bootstrap#19]
Hi,
I have a jsp with a form with theme set to bootstrap.
In the form I have an `<s:radio >` tag that maps to a property in a struts action whose setter method is annotated with the @RequiredFieldValidator annotation.
When I submit the form not having selected one of the radio buttons I obtain the required validation error but the tag generates two `<span>` tags one above the radio field and the other below.
The first span is defined as follow:
```
<span class="errorMessage">Specificare un ente</span>
```
as defined in template radiomap.ftl:
```
<#assign hasFieldErrors = fieldErrors?? && fieldErrors[parameters.name]??/>
<#if hasFieldErrors>
    <#list fieldErrors[parameters.name] as error>
    <span class="errorMessage">${error?html}</span><#t/>
    </#list>
</#if>
```
The second one is defined as follow:
```
<span class="glyphicon glyphicon-remove form-control-feedback"></span>
<span class="help-block alert-danger">Specificare un ente</span>
```
as defined in template controlfooter.ftl:
```
<#assign hasFieldErrors = parameters.name?? && fieldErrors?? && fieldErrors[parameters.name]??/>
<#if hasFieldErrors>
<span class="glyphicon glyphicon-remove form-control-feedback"></span>
    <#list fieldErrors[parameters.name] as error>
    <span class="help-block alert-danger">${error?html}</span><#t/>
    </#list>
</#if>
```
The problem is we have two equal messages one above and the other below.
I noticed the problem exists only for the tags: `<s:radio>`, `<s:checkbox>` and `<s:checkboxlist>` since they don't include the controlheader.ftl template. There's no similar problem for the `<s:select>`, `<s:text>` or `<s:textarea>` tags.

I tried commenting out the first `<span>` tag generation from the radiomap.ftl and the result was as expected.
There's a reason I'm missing for this behaviour ?
Thanks

**Comment by sdutry** [comment]
Created project that simulates the problem: [struts2-bootstrap-issue19](https://github.com/sdutry/struts2-bootstrap-issue19)

Created branch for fixing this issue: [issue19](https://github.com/sdutry/struts2-bootstrap/tree/issue19)

todolist:
- [ ] `s:radio`
- [ ] `s:checkbox`
- [ ] `s:checkboxlist`

**Comment by sdutry** [comment]
@jogep @max-trappist 

for fixing this issue concerning the double fielderror on `s:radio` in particular, i'm updating the `radiomap.ftl` to use the `controlheader.ftl` .

On first check this seems to solve the problem.
Was there a reason for this tag not to include the `controlheader.ftl` ?

The main reason i'm asking, is because this file was just changed to add support for dynamic attributes.
see issue #10 and pull-request #18 . This would basicaly remove the code recently added but should still keep the functionality.

**Comment by sdutry** [comment]
found an additional problem with `s:radio`

Adding cssClass attribute to the `s:radio` tag generates 2 class attributes on the input tag

**Comment by sdutry** [comment]
found an additional problem with `s:radio`

Ussing cssStyle adds it as plain text instead of as attribute to the div containing the input fields.

**Comment by sdutry** [comment]
Not using `controlheader.ftl` for the `radiomap.ftl`

**Comment by sdutry** [comment]
`s:checkbox` tag also doesn't work correctly with the attributes `cssStyle` and `cssClass`

**Comment by sdutry** [comment]
awaiting #20 to create a pull request

**Comment by jogep** [comment]
I close this issue as new version is released now.
