### ISSUE TITLE
set new development version (2.5.2-SNAPSHOT) for struts2-bootstrap

### ISSUE THREAD

**Issue by sdutry** [struts-community-plugins/struts2-bootstrap#20]
Update the version number in the `pom.xml` files to use the SNAPSHOT version of the upcoming release.

@jogep 
Can you do this please.
I don't know if you prefer this to be done in the master branch (the conventional way), or if you prefer making a new branch for the upcoming release and set it as the default branch (the way you work for `struts2-jquery` ).

**Comment by jogep** [comment]
@sdutry right now in the bootstrap plugin I used usually just the master brunch. Because the changes are usually smaller then in jquery plugin. But if you have larger changes feel free to create a separate branch.
