### ISSUE TITLE
Upgrade to Bootstrap 4.0

### ISSUE THREAD

**Issue by lukaszlenart** [struts-community-plugins/struts2-bootstrap#29]
A new version of Bootstrap is almost here, for now a `beta` version of Bootstrap 4.0 is available but I think this is a good point to start.

How can I help whit this?

**Comment by sdutry** [comment]
@lukaszlenart 
My suggestion would be to make a seperate branch for this until Bootstrap 4 is officialy released.

Preferably i'd like to have a new release with Bootstrap 3 (with the fixes so far and after the open pull request gets merged)

I think it would probably be best to update the minor version (2.6.x) or even the major version (3.0.x) for the Bootstrap 4. that way, if a bug is reported in the Bootstrap 3 version, we could still fix it without requiring people to move to Bootstrap 4.

But these are purely my opnions, i think we need to wait for some extra comments from @jogep .

**Comment by lukaszlenart** [comment]
Yes, I have the same idea, use 3.0 for the Bootstrap 4.0 within a separated branch

**Comment by jogep** [comment]
+1 for a minor release with latest bootstrap and fixes and then we could start on a separate branch with bootstrap 4.0.

**Comment by lukaszlenart** [comment]
Great :)

As I see all the issues related to 2.5.2 are almost addressed, how can I help with pushing out 2.5.2?

**Comment by jogep** [comment]
I will check if I can push a new version this weekend.

**Comment by jogep** [comment]
New version 2.5.2 is released now. I also created a branch for next development version release/3.0.x.

**Comment by sdutry** [comment]
Started a branch for this. see [issue29](https://github.com/sdutry/struts2-bootstrap/tree/issue29)

By the first looks, it's going to require a lot of changes.

**Comment by lukaszlenart** [comment]
I have started working on this locally, fixed few things. And yes, a lot of things has changed

**Comment by abrin** [comment]
Has progress on this plugin been abandoned? We're looking at upgrading to Bootstrap 4 and need to figure out how we'll accomplish it.

thanks

**Comment by lukaszlenart** [comment]
It's still a work in progress, see https://github.com/struts-community-plugins/struts2-bootstrap/pull/30

**Comment by abrin** [comment]
Hi Lukasz, thanks.  I hadn't seen any commits since December, so wasn't sure.  Is this something that might be done by the end of the year? 

thanks

**Comment by lukaszlenart** [comment]
Hope so :)

**Comment by sdutry** [comment]
@lukaszlenart 
I'm getting the following error while trying to run the showcase application.

```
    For "#if" condition: Expected a boolean, but this has evaluated to a string+extended_hash (String wrapped into f.e.b.StringModel):
==> parameters.labelposition!"" == 'inline'  [in template "template/bootstrap/simple/radiomap.ftl" at line 35, column 10]
```

https://github.com/struts-community-plugins/struts2-bootstrap/blob/ee0236cfaab520322838585b9b2140f24a6bf8c9/struts2-bootstrap-plugin/src/main/resources/template/bootstrap/simple/radiomap.ftl#L35-L37


any ideas what i might be missing?

**Comment by lukaszlenart** [comment]
Probably braces are needed `<#if (parameters.labelposition!"") == 'inline'>`

**Comment by sdutry** [comment]
@lukaszlenart 

> Probably braces are needed <#if (parameters.labelposition!"") == 'inline'>

that seems to be the problem indeed.

**Comment by abrin** [comment]
fyi -- we've been on a different timeline and have focused on rolling our own.  you may be able to borrow some pieces from this branch -- https://bitbucket.org/tdar/tdar.src/src/feature-bootstrap/web/src/main/resources/template/bootstrap4/ .  it's not perfect, but seems to be working pretty nicely thus far.

**Comment by jogep** [comment]
I finally found some time to adjust everything to bootstrap 4 and released a initial version.
