### ISSUE TITLE
Struts 7 Support

### ISSUE THREAD

**Issue by dja557** [struts-community-plugins/struts2-bootstrap#295]
There is an issue the integration of Spring Boot `3.3.3`, Struts2 `7.0.0-M9` and`struts2-bootstrap-plugin` version `4.0.3` when attempting to render a JSP. It seems that some interfaces and implementations need to be updated to work with the new `jakarta.*` APIs.

```
java.lang.AbstractMethodError: Receiver class com.jgeppert.struts2.bootstrap.views.BootstrapTagLibrary does not define or inherit an implementation of the resolved method 'abstract java.lang.Object getModels(com.opensymphony.xwork2.util.ValueStack, jakarta.servlet.http.HttpServletRequest, jakarta.servlet.http.HttpServletResponse)' of interface org.apache.struts2.views.TagLibraryModelProvider.
```

**Comment by lukaszlenart** [comment]
I don't plan to upgrade 4.x version to be compatible with Struts 7, too much hassle

**Comment by gregh3269** [comment]
PR's are welcome?

**Comment by lukaszlenart** [comment]
Sure :)

**Comment by dja557** [comment]
> I don't plan to upgrade 4.x version to be compatible with Struts 7, too much hassle

Ok, thanks for replying!
