### ISSUE TITLE
Error message position

### ISSUE THREAD

**Issue by lukaszlenart** [struts-community-plugins/struts2-bootstrap#3]
Is it possible to define position of error message? ie. not only below a control, but on right in the same line.

**Comment by jogep** [comment]
Right now it is not possible. The errors are only shown below the field.

**Comment by lukaszlenart** [comment]
Would it be hard to prepare to change that? I would like to prepare a PR if you could you push me in a right direction :)

**Comment by jogep** [comment]
You don't need to create a PR you already have write permissions. ;-)

Problem is we need a control to define the form grid. The result could look like this:
<http://plnkr.co/gmf2nKNOBAhKuPLzOYco>

Per default the label width is col-sm-3 and the element width is col-sm-9.
So if someone like to have the the help-block on the right side like in example above we need a parameter in the form tag which overwrite the defaults.

Another way would be the user creates his own theme override for controlheader-core.ftl and controlfooter.ftl.

**Comment by lukaszlenart** [comment]
> controlheader-core.ftl and controlfooter.ftl

hmm... good idea, will try that first :)

**Comment by jogep** [comment]
is this still needed?
