### ISSUE TITLE
update showcase application to bootstrap 4

### ISSUE THREAD

**Issue by sdutry** [struts-community-plugins/struts2-bootstrap#36]
issue to list all things that need to be fixed in the showcase application due to bootstrap 4 migration

- [x] update navbar html
- [ ] make navbar toggle work
- [x] update submenu on the left
- [x] remove margin from messages (actionerror, actionmessage and fielderror)
- [ ] Form horizontal looks same like vertical
- [ ] The buttons for the struts2 components input transfer are not shown anymore
- [ ] make tooltips work again

relates to 
- #35 
- #29

**Comment by jogep** [comment]
@sdutry please check with latest version https://struts.jgeppert.com/struts2-bootstrap-showcase/index.action I adjusted most things to work with bootstrap 4.
