### ISSUE TITLE
field errors dont go after doing ajax submit on form with validation. 

### ISSUE THREAD

**Issue by mrmaniac2416** [struts-community-plugins/struts2-bootstrap#38]
all the field errors which were generated while trying to fill a form styled with bootstrap dont disappear after doing ajax submit on the form . 
But using normal xhtml form , it works as expeced

**Comment by jogep** [comment]
Can you please try with latest version? The field errors are shown to me in my tests.

**Comment by jogep** [comment]
Fixed in latest available version.
