### ISSUE TITLE
Reference other bootstrap theme templates using parameters.expandTheme rather than directly

### ISSUE THREAD

**Issue by perfnorm** [struts-community-plugins/struts2-bootstrap#6]
For example, use:
`<#include "/${parameters.templateDir}/${parameters.expandTheme}/controlheader.ftl" />`

rather than:
`<#include "/${parameters.templateDir}/bootstrap/controlheader.ftl" />`

This will make extending the theme much easier.

**Comment by jogep** [comment]
This is fixed with just released version 4.0.1.
