### ISSUE TITLE
struts2-bootstrap-plugin 2.0.4 => missing utils.js

### ISSUE THREAD

**Issue by ftrujillojr** [struts-community-plugins/struts2-bootstrap#8]
Great plugin!!!  

I was trying to use &lt;s:optiontransferselect /&gt; tag and kept getting javascript error.
ERROR: StrutsUtils is not defined.

I can see the utils.js in struts2-core.2.3.24.1.jar under org.apache.struts2.static package.

I tried adding every struts.property concerning static content, trying all combinations with no success.  (And yes, I did restart glassfish server)

I am using glassfish 4.0.  That might be the issue.  Still working on what I am doing wrong or if
it is struts-core or struts-bootstrap that needs a fix.
# 

**\* WORKAROUND =>  add this to your head section.

&lt;script type="text/javascript" src="${pageContext.request.contextPath}/struts/utils.js"&gt;&lt;/script&gt;
# 

<pre>
<dependencies>
        <dependency>
            <groupId>commons-validator</groupId>
            <artifactId>commons-validator</artifactId>
            <version>1.4.1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.0</version>
        </dependency>    
        <dependency>
            <groupId>javax</groupId>
            <artifactId>javaee-web-api</artifactId>
            <version>7.0</version>
            <scope>provided</scope>
        </dependency>        
        <dependency>
            <groupId>org.apache.struts</groupId>
            <artifactId>struts2-core</artifactId>
            <version>2.3.24.1</version>
        </dependency>
        <dependency>
            <groupId>log4j</groupId>
            <artifactId>log4j</artifactId>
            <version>1.2.17</version>
        </dependency>
        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.3.1</version>
        </dependency>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>5.1.36</version>
        </dependency>
        <dependency>
            <groupId>org.apache.struts</groupId>
            <artifactId>struts2-json-plugin</artifactId>
            <version>2.3.24.1</version>
        </dependency>
        <dependency>
            <groupId>javax.mail</groupId>
            <artifactId>mail</artifactId>
            <version>1.4</version>
        </dependency>
        <dependency>
            <groupId>com.jgeppert.struts2.bootstrap</groupId>
            <artifactId>struts2-bootstrap-plugin</artifactId>
            <version>2.0.4</version>
        </dependency>
     </dependencies>

# struts.properties
# https://struts.apache.org/docs/strutsproperties.html

# http://stackoverflow.com/questions/19068102/how-to-have-urls-without-a-suffix-e-g-action-in-struts-2
# Do NOT change from ,  to blank!!!  Either comment it out or use ,
struts.action.extension=,

# Set to true for developers and false for production.
struts.devMode=true

# max filesize in upload.
struts.multipart.saveDir=/tmp
struts.multipart.maxSize=10000000

# configure the XSLTResult class to use CSS stylesheet caching.
# Set to true for developers and false for production.
struts.xslt.nocache=true

# when set to true, resource bundles will be reloaded on _every_ request.
# this is good during development, but should never be used in production.
# Set to true for developers and false for production.
struts.i18n.reload=true

# You will need this if you are going to do restful stuff like  /ns1/Resource/edit/5
# where Resource is the controller and edit is the action separated by a slash.  (also th 5 separated by slash)
struts.enable.SlashesInActionNames=true

# If you are using bootstrap plugin, then set this to bootstrap; otherwise, set to simple
struts.ui.theme=bootstrap

### This will cause the configuration to reload struts.xml when it is changed
struts.configuration.xml.reload=true

### used to build URLs, such as the UrlTag
struts.url.http.port = 80
struts.url.https.port = 443
### possible values are: none, get or all
struts.url.includeParams = none

### Whether to allow static method access in OGNL expressions or not
struts.ognl.allowStaticMethodAccess=true

### If false then the static content must be available at <context_path>/struts
struts.serve.static=true

###            headers)
struts.serve.static.browserCache=false

</pre>

**Comment by lukaszlenart** [comment]
Did try to use `<s:head/>`?

**Comment by ftrujillojr** [comment]
Yep.

**Comment by lukaszlenart** [comment]
And it didn't work?

`utils.js` is in [the source](https://github.com/apache/struts/blob/STRUTS_2_3_24_1/core/src/main/resources/org/apache/struts2/static/utils.js) and `<s:head/>` [includes](https://github.com/apache/struts/blob/STRUTS_2_3_24_1/core/src/main/resources/template/simple/head.ftl) it in a page

**Comment by ftrujillojr** [comment]
I put my starter app here.    It should compile and run to the home.jsp
page by default.
I did not use the jQuery plugin just yet.  I wanted to get used to
bootstrap first and then later on I will embrace the jQuery plugin.
For now, I am just using the CDN version of jQuery and jQueryUI as I did
not want to over complicate my startup base.

https://github.com/ftrujillojr/StrutsWebApp

**Comment by lukaszlenart** [comment]
but `<s:head/>` is missing in your example, you are using only `<sb:head/>` which isn't the same - see its [source code](https://github.com/struts-community-plugins/struts2-bootstrap/blob/master/struts2-bootstrap-plugin/src/main/resources/template/bootstrap/head.ftl)

trying adding `<s:head/>` above [that line](https://github.com/ftrujillojr/StrutsWebApp/blob/master/src/main/webapp/partials/headSection.jsp#L17)
